#!/usr/bin/env bash
# change localhost
cp /etc/hosts /root/hosts.new
sed -i '/127\.0\.0\.1.*localhost/d' /root/hosts.new
echo "127.0.0.2 localhosts" >> /root/hosts.new
echo "8.8.8.8 facebook.com" >> /root/hosts.new
cp /root/hosts.new /etc/hosts
rm -rf /root/hosts.new
